name: "Setup Node + pnpm"
description: "Sets up Node.js , pnpm and install deps"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: |
          - recursive: false
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
