name: CI

on:
  push:
    branches:
      - feature/*
      - feat/*
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "eslint.config.mjs"
      - "next-env.d.ts"
      - "next.config.ts"
      - "postcss.config.mjs"
      - ".eslintrc*"
      - ".prettierrc*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm check
