name: CI

on:
  push:
    branches:
      - feature/*
      - feat/*
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "eslint.config.mjs"
      - "next-env.d.ts"
      - "next.config.ts"
      - "postcss.config.mjs"
      - ".eslintrc*"
      - ".prettierrc*"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1

jobs:


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          node-version: 20
      - run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          node-version: 20

      - run: pnpm format:check

  typecheck:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          node-version: 20

      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          node-version: 20

      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: pnpm build
